Update Workflow to Fail Build if Package PyTests fail

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,4 +1,3 @@
-
 name: Build and Test Package
 
 on:
@@ -25,7 +24,7 @@ jobs:
     - name: Install build dependencies
       run: |
         python -m pip install --upgrade pip
-        python -m pip install build setuptools wheel
+        python -m pip install build setuptools wheel pytest
     
     - name: Build package
       run: python -m build
@@ -36,7 +35,25 @@ jobs:
     - name: List installed packages
       run: pip list
 
+    - name: Run tests on installed package
+      run: |
+        mkdir test_dir
+        cp -r tests/ test_dir/
+        cd test_dir
+        
+        python -m pytest tests/
+        test_exit_code=$?
+        
+        cd ..
+        rm -rf test_dir
+        
+        if [ $test_exit_code -ne 0 ]; then
+          echo "Tests failed!"
+          exit 1
+        fi
+
     - name: Upload built package as artifact
+      if: success()
       uses: actions/upload-artifact@v4
       with:
         name: dist-${{ matrix.python-version }}
